name: Run pytest

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start Docker Compose
      id: start_docker_compose
      run: |
        docker-compose -f docker-compose.dev.yml up -d
        CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' laraflask_development)
        echo "CONTAINER_IP=$CONTAINER_IP" >> $GITHUB_ENV
        echo $GITHUB_ENV

    - name: Get CONTAINER IP
      run: |
        echo $CONTAINER_IP

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest for laraflask
      env:
        CONTAINER_IP: ${{ env.CONTAINER_IP }}
      run: |
        pytest tests/test_routes_laraflask.py

    - name: Stop Docker Compose
      run: docker-compose -f docker-compose.dev.yml down
