name: Run pytest

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Start Docker Compose
      run: |
        docker-compose -f docker-compose.dev.yml up -d
        export CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <container_name_or_id>)

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest for laraflask
      env:
        CONTAINER_IP: $CONTAINER_IP
      run: |
        pytest --container-ip=$CONTAINER_IP test/test_laraflask.py

    - name: Stop Docker Compose
      run: docker-compose -f docker-compose.dev.yml down
